name = "quick-notes-cloudflare-workers"
main = "worker/src/index.ts"
compatibility_date = "2023-12-18"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "quick-notes-db"
database_id = "25c84f83-f374-47ea-bd61-9e35f2b91df6"

# Durable Objects for session management
[[durable_objects.bindings]]
name = "SESSIONS"
class_name = "SessionDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["SessionDurableObject"]